# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfor < Formula
  desc "AI-powered terminal assistant for command lookups"
  homepage "https://github.com/cowboy-bebug/cfor"
  version "0.1.0"
  license "MIT"

  depends_on "git"
  depends_on "go" => "^1.24"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cowboy-bebug/cfor/releases/download/v0.1.0/cfor_v0.1.0_darwin_amd64.tar.gz"
      sha256 "00a585bd0b6ec12219827025949f984b8bd30830a4759a87ddf4f35f2db26ba8"

      def install
        bin.install "cfor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cowboy-bebug/cfor/releases/download/v0.1.0/cfor_v0.1.0_darwin_arm64.tar.gz"
      sha256 "e055a95cf3be81ccd949359feeba684d10edd65c978390ce5f5f801d781020ef"

      def install
        bin.install "cfor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cowboy-bebug/cfor/releases/download/v0.1.0/cfor_v0.1.0_linux_amd64.tar.gz"
        sha256 "17ce28f90d273fe3f75e79140ac13f55fd3e96f82ef49423a56035952cb1a9d6"

        def install
          bin.install "cfor"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cowboy-bebug/cfor/releases/download/v0.1.0/cfor_v0.1.0_linux_arm64.tar.gz"
        sha256 "ed27c1020a792c45a3d73abbf84cacf87259a8d839573d3ce80d3b8f3ed2ed04"

        def install
          bin.install "cfor"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To begin using cfor, you must set up either OpenAI API key:
        export OPENAI_API_KEY="sk-..."

      Or use a dedicated key for cfor:
        export CFOR_OPENAI_API_KEY="sk-..."

      And optionally switch between supported models (default is gpt-4o):
        export CFOR_OPENAI_MODEL="gpt-4o"
    EOS
  end

  test do
    system "#{bin}/cfor", "version"
  end
end
