# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kommit < Formula
  desc "Therapeutic approach to git commits with AI-generated messages"
  homepage "https://github.com/cowboy-bebug/kommit"
  version "0.2.0"
  license "MIT"

  depends_on "git"
  depends_on "go" => "^1.24"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cowboy-bebug/kommit/releases/download/v0.2.0/kommit_v0.2.0_darwin_amd64.tar.gz"
      sha256 "9488218857b6e0259d92ee7877c0d51be44808fb269e96d6e61bafb927d92b54"

      def install
        bin.install "git-kommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cowboy-bebug/kommit/releases/download/v0.2.0/kommit_v0.2.0_darwin_arm64.tar.gz"
      sha256 "9136cfbe81b45e794645920fac8781210011a51c958310f34b888ea13be720c2"

      def install
        bin.install "git-kommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cowboy-bebug/kommit/releases/download/v0.2.0/kommit_v0.2.0_linux_amd64.tar.gz"
        sha256 "7512a574c12fdd5db54eaa1c606c85e7e60b67cf44d15bdbb30dcfe85dd43881"

        def install
          bin.install "git-kommit"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cowboy-bebug/kommit/releases/download/v0.2.0/kommit_v0.2.0_linux_arm64.tar.gz"
        sha256 "ce5f8e2f0f276cd313a032a1285397567f64e8c9d72bd05dd00a9e041f27f79e"

        def install
          bin.install "git-kommit"
        end
      end
    end
  end

  def caveats
    <<~EOS
      🧐 Your therapist is ready for session!

      To begin your repository's healing journey:
        git kommit init

      Remember to set your OpenAI API key:
        export OPENAI_API_KEY=your_openai_api_key

      Or use a dedicated key for Kommit:
        export KOMMIT_API_KEY=your_kommit_specific_key
    EOS
  end

  test do
    system "#{bin}/git", "kommit", "version"
  end
end
