# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kommit < Formula
  desc "Therapeutic approach to git commits with AI-generated messages"
  homepage "https://github.com/cowboy-bebug/kommit"
  version "0.1.2"
  license "MIT"

  depends_on "git"
  depends_on "go" => "^1.24"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cowboy-bebug/kommit/releases/download/v0.1.2/kommit_v0.1.2_darwin_amd64.tar.gz"
      sha256 "ff313b8b414f48bb61d54f544fefc8f21e0158d47adad7d7d33df0e908ef27d9"

      def install
        bin.install "git-kommit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cowboy-bebug/kommit/releases/download/v0.1.2/kommit_v0.1.2_darwin_arm64.tar.gz"
      sha256 "f2d5ee36dc63c13ccac00cbdbc0e0709d3c8632c2ca7a1950190f13120edec5f"

      def install
        bin.install "git-kommit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cowboy-bebug/kommit/releases/download/v0.1.2/kommit_v0.1.2_linux_amd64.tar.gz"
        sha256 "b2d52b554954c44ff40ac1e183120b10573ee2b35bc7b6a0fd45042efca2c6d2"

        def install
          bin.install "git-kommit"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cowboy-bebug/kommit/releases/download/v0.1.2/kommit_v0.1.2_linux_arm64.tar.gz"
        sha256 "8f7aac01ea5fd688d360b4a11e92c28b5885b8aee41592ef9853d89a837d0cb9"

        def install
          bin.install "git-kommit"
        end
      end
    end
  end

  def caveats
    <<~EOS
      🧐 Your therapist is ready for session!

      To begin your repository's healing journey:
        git kommit init

      Remember to set your OpenAI API key:
        export OPENAI_API_KEY=your_openai_api_key

      Or use a dedicated key for Kommit:
        export KOMMIT_API_KEY=your_kommit_specific_key
    EOS
  end

  test do
    system "#{bin}/git", "kommit", "version"
  end
end
